[package]
name = "enum_values"
version = "0.3.0"
authors = ["cedric"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.14"
quote = "1.0.2"

[lib]
proc-macro = true